from django.conf.urls import url

from decisiontree import views


urlpatterns = [
    url(r'^$',
        views.SurveyList.as_view(),
        name='list-surveys'),
    url(r'^(?P<pk>\d+)/$',
        views.SurveyCreateUpdate.as_view(),
        name='insert_tree'),
    url(r'^(?P<pk>\d+)/report/$',
        views.SurveyReport.as_view(),
        name='survey-report'),
    url(r'^(?P<pk>\d+)/report/sessions/$',
        views.SurveySessions.as_view(),
        name='recent_sessions'),
    url(r'^data/add/$',
        views.SurveyCreateUpdate.as_view(),
        name='add_tree'),
    url(r'^data/export/(?P<pk>\d+)/$',
        views.SurveyExport.as_view(),
        name='export_tree'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.SurveyDelete.as_view(),
        name='delete_tree'),

    url(r'^entry/list/$',
        views.EntryList.as_view(),
        name='list-entries'),
    url(r'^entry/(?P<pk>\d+)/edit/$',
        views.EntryUpdate.as_view(),
        name='update-entry'),

    url(r'^survey/answer/list/$',
        views.AnswerList.as_view(),
        name='answer_list'),
    url(r'^survey/answer/add/$',
        views.AnswerCreateUpdate.as_view(),
        name='add_answer'),
    url(r'^survey/answer/update/(?P<pk>\d+)/$',
        views.AnswerCreateUpdate.as_view(),
        name='insert_answer'),
    url(r'^survey/answer/delete/(?P<pk>\d+)/$',
        views.AnswerDelete.as_view(),
        name='delete_answer'),

    url(r'^survey/path/list/$',
        views.PathList.as_view(),
        name='path_list'),
    url(r'^survey/path/add/$',
        views.PathCreateUpdate.as_view(),
        name='add_path'),
    url(r'^survey/path/update/(?P<pk>\d+)/$',
        views.PathCreateUpdate.as_view(),
        name='insert_path'),
    url(r'^survey/path/delete/(?P<pk>\d+)/$',
        views.PathDelete.as_view(),
        name='delete_path'),

    url(r'^survey/question/list/$',
        views.QuestionList.as_view(),
        name='list-questions'),
    url(r'^survey/question/add/$',
        views.QuestionCreateUpdate.as_view(),
        name='add_question'),
    url(r'^survey/question/update/(?P<pk>\d+)/$',
        views.QuestionCreateUpdate.as_view(),
        name='insert_question'),
    url(r'^survey/question/delete/(?P<pk>\d+)/$',
        views.QuestionDelete.as_view(),
        name='delete_question'),

    url(r'^survey/state/list/$',
        views.StateList.as_view(),
        name='state_list'),
    url(r'^survey/state/add/$',
        views.StateCreateUpdate.as_view(),
        name='add_state'),
    url(r'^survey/state/update/(?P<pk>\d+)/$',
        views.StateCreateUpdate.as_view(),
        name='insert_state'),
    url(r'^survey/state/delete/(?P<pk>\d+)/$',
        views.StateDelete.as_view(),
        name='delete_state'),

    url(r'^tags/list/$',
        views.TagList.as_view(),
        name='list-tags'),
    url(r'^tags/create/$',
        views.TagCreateUpdate.as_view(),
        name='create-tag'),
    url(r'^tags/(?P<pk>\d+)/edit/$',
        views.TagCreateUpdate.as_view(),
        name='edit-tag'),
    url(r'^tags/(?P<pk>\d+)/delete/$',
        views.TagDelete.as_view(),
        name='delete-tag'),
]
