# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0004_answer_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestate',
            name='answer_retries',
            field=models.BooleanField(default=True, help_text=b"Whether respond user with num_retries leftalso includes 'error_response' hints."),
        ),
    ]
