# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0005_treestate_answer_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='success_response',
            field=models.CharField(blank=True, help_text=b'Optional message to send if the question is answered properly.', max_length=160),
        ),
        migrations.AlterField(
            model_name='treestate',
            name='answer_retries',
            field=models.BooleanField(default=True, help_text=b"Whether respond user with num_retries leftalso includes this queston's 'error_response' hints."),
        ),
    ]
